const data = {
    products: [
        {
            _id: "dress1",
            name: "H&M baby clothing",
            image: "/images/dress1.jpg",
            description: "short sleeves, high quality and 100% cotton",
            availablesizes: ["74", "80", "86", "92", "98"],
            color: ["pink","blue"],
            price: 26,
            category: "dresses",
            brand: "H&M",
            rating: "4.0",
            numReview: "10"

        },
        {
            _id: "dress2",
            name: "C&A baby cothing",
            image: "/images/dress2.jpg",
            description: "short sleeves, high guality and 100% cotton",
            availablesizes: ["92", "98", "104", "104", "110"],
            color: ["yellow", "black"],
            price: 17.99,
            category: "dresses",
            brand: "C&A",
            rating: "4.5",
            numReview: "10"
        },
        {
            _id: "dress3",
            name: "HEMA baby clothing",
            image: "/images/dress3.jpg",
            description: "short sleeves high quality and 100% cotton",
            availablesizes: ["92", "98", "104"],
            color: ["blue"],
            price: 12,
            category: "dresses",
            brand: "HEMA",
            rating: "4.5",
            numReview: "15",
            
        },
        {
            _id: "dress4",
            name: "Mamaloes baby clothing",
            image: "/images/dress4.jpg",
            description: "short sleeves, high quality and 100% cotton",
            availablesizes: ["62", "68", "74", "80", "86"],
            color: ["blue"],
            price: 34,
            category: "dresses",
            brand: "Mamaloes",
            rating: "4.0",
            numReview: "17",
        },
        {
            _id: "dress5",
            name: "Carter's baby clothing",
            image: "/images/dress5.jpg",
            description: "short sleeves, high quality and 100% cotton",
            availablesizes: ["86", "92", "98", "104"],
            color: ["yellow", "white"],
            price: 37,
            category: "dresses",
            brand: "Carter's",
            rating: "4.0",
            numReview: "17",
            
        },
        {
            _id: "dress6",
            name: "Cat & Jack baby clothing",
            image: "/images/dress6.jpg",
            description: "short sleeves, high quality and 100% cotton",
            availablesizes: ["62", "68", "74", "80", "86"],
            color: ["yellow", "pink"],
            price: 29.99,
            category: "dresses",
            brand: "Cat & Jack",
            rating: "4.8",
            numReview: "16",
            
        },
        {
            _id: "dress7",
            name: "Burt's bees baby short clothing",
            image: "/images/dress7.jpg",
            description: "short sleeves, high quality and 100% cotton",
            availablesizes: ["62", "68", "74", "80", "86"],
            color: ["blue", "yellow", "pink", "green"],
            price: 15,
            category: "dresses",
            brand: "Burt's bees baby",
            rating: "4.0",
            numReview: "10",
           
        },
        {
            _id: "dress8",
            name: "Bees baby long dress",
            image: "/images/dress8.jpg",
            description: "short sleeves, high quality and 100% cotton",
            availablesizes: ["92", "98", "104", "110"],
            color: ["blue", "pink"],
            price: 17.99,
            category: "dresses",
            brand: "Bees baby",
            rating: "4.5",
            numReview: "18",
            
        },
        {
            _id: "dress9",
            name: "Babydump short dress",
            image: "/images/dress9.jpg",
            description: "short sleeves, high quality and 100% cotton",
            availablesizes: ["92", "98", "104", "110"],
            color: ["black", "yellow"],
            price: 19.99,
            category: "dresses",
            brand: "Babydump baby",
            rating: "4.0",
            numReview: "17",
            
        },
        {
            _id: "dress10",
            name: "C&A baby short dress",
            image: "/images/dress10.jpg",
            description: "short sleeves, high quality and 100% cotton",
            availablesizes: ["98", "104", "110"],
            color: ["black", "white"],
            price: 22.99,
            category: "dresses",
            brand: "C&A",
            rating: "4.5",
            numReview: "15",
            
        },
        {
            _id: "dress11",
            name: "H&M baby long dress",
            image: "/images/dress11.jpg",
            description: "long sleeves, high quality and 100% cotton",
            availablesizes: [ "86","92", "98", "104", "110"],
            color: ["pink", "green"],
            price: 19.99,
            category: "dresses",
            brand: "H&M",
            rating: "4.8",
            numReview: "18",
            
        }
    ]
} 
export default data;